services:
  - type: web
    name: lw-tech-web
    runtime: static
    rootDir: .
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html